config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sales
  root "sales#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
    
    def self.last_sales_12_month
        Sale.where(created_at: 12.months.ago..Date.today)
        .group("strftime('%m-%Y', created_at)")
        .order(created_at: :asc)
        .sum(:amount)
    end

    def self.last_sales_12_month_count
        Sale.where(created_at: 12.months.ago..Date.today)
        .group("strftime('%m-%Y', created_at)")
        .order(created_at: :asc)
        .count
    end

    def self.average_sales_last_12_month
        Sale.where(created_at: 12.months.ago..Date.today)
        .group("strftime('%m-%Y', created_at)")
        .order(created_at: :asc)
        .average(:amount)
    end

    def self.last_sales(months, column)
        Sale.where(created_at: months.months.ago..Date.today)
        .group(column)
        .count
    end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    @last_12_months_amount = Sale.last_sales_12_month
    @last_12_months_amount_count = Sale.last_sales_12_month_count
    @average_sales_last_12_month = Sale.average_sales_last_12_month
    @last_sales_12_month_origin_count = Sale.last_sales(12, :origin)
    @last_sales_6_month_origin_count = Sale.last_sales(6, :origin)
    @last_sales_3_month_origin_count = Sale.last_sales(3, :origin)
    @last_sales_1_month_origin_count = Sale.last_sales(1, :origin)
    @last_sales_12_month_blend_count = Sale.last_sales(12, :blend_name)
    @last_sales_6_month_blend_count = Sale.last_sales(6, :blend_name)
    @last_sales_3_month_blend_count = Sale.last_sales(3, :blend_name)
    @last_sales_1_month_blend_count = Sale.last_sales(1, :blend_name)
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:amount, :blend_name, :origin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DashboardCafeteria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :blend_name %>
    <%= form.text_field :blend_name %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dashboard de Ventas</h1>
<br>

  <div> 
    <h2>Ventas mensuales ultimos 12 meses</h2>
    <%= column_chart @last_12_months_amount %>
  </div>
  <div> 
    <h2>Cantidad ventas mensuales ultimos 12 meses</h2>
    <%= column_chart @last_12_months_amount_count %>
  </div>
  <div> 
    <h2>Promedio ventas mensuales ultimos 12 meses</h2>
    <%= column_chart @average_sales_last_12_month %>
  </div>
  <div> 
    <h2>Cantidad de ventas segun su origen de los ultimos 12 meses</h2>
    <%= pie_chart @last_sales_12_month_origin_count %>
  </div>
  <div> 
    <h2>Cantidad de ventas segun su origen de los ultimos 6 meses</h2>
    <%= pie_chart @last_sales_6_month_origin_count %>
  </div>
  <div> 
    <h2>Cantidad de ventas segun su origen de los ultimos 3 meses</h2>
    <%= pie_chart @last_sales_3_month_origin_count %>
  </div>
  <div> 
    <h2>Cantidad de ventas segun su origen del ultimo mes</h2>
    <%= pie_chart @last_sales_1_month_origin_count %>
  </div>
  <div> 
    <h2>Cantidad de ventas por blend name de los ultimos 12 meses</h2>
    <%= pie_chart @last_sales_12_month_blend_count %>
  </div>
  <div> 
    <h2>Cantidad de ventas por blend name de los ultimos 6 meses</h2>
    <%= pie_chart @last_sales_6_month_blend_count %>
  </div>
  <div> 
    <h2>Cantidad de ventas por blend name de los ultimos 3 meses</h2>
    <%= pie_chart @last_sales_3_month_blend_count %>
  </div>
  <div> 
    <h2>Cantidad de ventas por blend name del ultimo mes</h2>
    <%= pie_chart @last_sales_3_month_blend_count %>
  </div>
<br>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @sale.amount %>
</p>

<p>
  <strong>Blend name:</strong>
  <%= @sale.blend_name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @sale.origin %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>